import { Smile, ArrowLeft, AlertCircle, Search, Sparkles, Play, HelpCircle, Link as LinkIcon } from "lucide-react"
import Link from "next/link"

/**
 * Emotional System Page
 *
 * Your Body's Meaning Maker - mental wellbeing, mood regulation, psychological health
 * Part of the bioEDGE Decoder 15 Systems Framework.
 */
export default function EmotionalSystemPage() {
  return (
    <>
      {/* Hero */}
      <div className="be-event-hero">
        <div className="be-container py-16 relative z-10">
          
            <Link
              href="/systems"
              className="inline-flex items-center gap-2 text-sm text-white/70 hover:text-gold transition-colors mb-6"
            >
              <ArrowLeft className="h-4 w-4" />
              Back to All Systems
            </Link>
            <div className="flex items-center gap-3 mb-4">
              <Smile className="h-10 w-10 text-gold" />
              <h1 className="font-heading text-4xl md:text-5xl font-bold tracking-tight text-white">
                Emotional System
              </h1>
            </div>
            <p className="text-xl text-white/80">
              Your Body&apos;s Meaning Maker
            </p>
            <p className="text-sm text-gold mt-4 font-heading uppercase tracking-wider">
              bioEDGE Decoder
            </p>
        </div>
      </div>

      {/* Content */}
      <div className="be-container py-12">
        <div className="space-y-12">

          {/* Section 1: Natural Intelligence */}
          <section>
            <div className="flex items-center gap-3 mb-6">
              <span className="flex items-center justify-center w-10 h-10 rounded-full bg-navy text-white font-heading font-bold">1</span>
              <h2 className="section-title">Natural Intelligence</h2>
            </div>
            <div className="be-card space-y-4 body-text">
              <p>
                The Emotional System governs the felt experience of being alive. It takes raw experience and transforms it into meaning you can feel.
              </p>
              <p>
                This system processes. Not just information, but sensation. Not just events, but their significance to you. When something happens, this system tells you what it means before your thinking mind has a chance to analyze it.
              </p>
              <p className="font-semibold text-navy">
                What makes this system unique among the fourteen: it is where experience becomes personal. The Stress System might tell your body there&apos;s danger. The Consciousness System might observe what&apos;s happening. But the Emotional System is where you feel that danger as fear, where you experience that observation as wonder or dread or curiosity. It&apos;s the difference between knowing something and feeling it.
              </p>
              <p>
                Emotions are not character flaws. They are not chemical imbalances to be corrected. They are embodied states with clear biological signatures, generated by brain structures including the amygdala, hippocampus, and insula. Antonio Damasio demonstrated in the 1990s that emotions are essential to rational decision-making, not obstacles to it. People with damage to emotion-processing brain regions don&apos;t become more logical. They become less able to make decisions at all.
              </p>
              <p>
                Here is your psychophysiological supersystem at work: the same chemical messengers that signal your immune system to respond to threat also shift your emotional state. The hormones that regulate your metabolism also color your mood. The nervous system that governs your stress response also determines whether you can access feelings of safety and connection. These systems don&apos;t hold committee meetings. They communicate constantly through shared messengers and feedback loops so integrated that affecting one inevitably affects the others.
              </p>
              <p>
                Your body already knows how to feel. You were born with this capacity intact. Before you had words, you had feelings. Before you could name what was happening, you could sense its meaning. This wisdom is encoded in your biology, not in concepts, but in what your nervous system knows how to do.
              </p>
              <p className="text-electric-blue font-medium">
                The question isn&apos;t whether your emotional system is working. It&apos;s whether you&apos;re able to hear what it&apos;s telling you.
              </p>
            </div>
          </section>

          {/* Section 2: Eliminate */}
          <section>
            <div className="flex items-center gap-3 mb-6">
              <span className="flex items-center justify-center w-10 h-10 rounded-full bg-navy text-white font-heading font-bold">2</span>
              <h2 className="section-title">Eliminate</h2>
            </div>
            <p className="body-text mb-6">
              These are factors worth examining. Not causes. Not diagnoses. Simply elements that may be interfering with your emotional system&apos;s natural function.
            </p>

            <div className="grid gap-6 md:grid-cols-2">
              {/* Lifestyle Factors */}
              <div className="be-card">
                <h3 className="font-heading font-bold text-navy mb-4">Lifestyle Factors</h3>
                <ul className="space-y-3 body-text">
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Sleep deprivation amplifying emotional volatility and overwhelm</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Sedentary patterns associated with stuck emotional states</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Calendar with no margin leaving no space for emotional processing</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Feelings accumulating when there&apos;s no time to feel them</span></li>
                </ul>
              </div>

              {/* Dietary Considerations */}
              <div className="be-card">
                <h3 className="font-heading font-bold text-navy mb-4">Dietary Considerations</h3>
                <ul className="space-y-3 body-text">
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Blood sugar fluctuations influencing emotional regulation</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Alcohol, excessive caffeine affecting mood and processing</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Highly processed foods associated with emotional volatility</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Gut health influencing emotional states through gut-brain axis</span></li>
                </ul>
              </div>

              {/* Environmental Interference */}
              <div className="be-card">
                <h3 className="font-heading font-bold text-navy mb-4">Environmental Interference</h3>
                <ul className="space-y-3 body-text">
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Chronic noise, clutter, or chaos contributing to overwhelm</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Toxic environments (mold, chemicals) affecting mood through inflammation</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Limited natural light affecting emotional experience</span></li>
                </ul>
              </div>

              {/* Relationship & Emotional Patterns */}
              <div className="be-card">
                <h3 className="font-heading font-bold text-navy mb-4">Relationship &amp; Emotional Patterns</h3>
                <ul className="space-y-3 body-text">
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Relationships where emotional expression is unwelcome</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Unresolved relational wounds keeping system in protective patterns</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Chronic loneliness affecting emotional health</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Past betrayals or invalidations shaping current accessibility</span></li>
                </ul>
              </div>

              {/* Habitual Patterns */}
              <div className="be-card">
                <h3 className="font-heading font-bold text-navy mb-4">Habitual Patterns</h3>
                <ul className="space-y-3 body-text">
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Chronic suppression leading to numbness or explosive outbursts</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Emotional avoidance through busyness, substances, or distraction</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Habitual emotional roles (&quot;strong one,&quot; &quot;caretaker&quot;) suppressing needs</span></li>
                </ul>
              </div>

              {/* Digital Interference */}
              <div className="be-card">
                <h3 className="font-heading font-bold text-navy mb-4">Digital Interference</h3>
                <ul className="space-y-3 body-text">
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Screen time interfering with quieter emotional processing</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Social media comparison contributing to shame or inadequacy</span></li>
                  <li className="flex gap-2"><AlertCircle className="h-4 w-4 text-gold flex-shrink-0 mt-0.5" /><span>Notification patterns fragmenting attention needed for processing</span></li>
                </ul>
              </div>
            </div>
          </section>

          {/* Section 3: Decode */}
          <section>
            <div className="flex items-center gap-3 mb-6">
              <span className="flex items-center justify-center w-10 h-10 rounded-full bg-navy text-white font-heading font-bold">3</span>
              <h2 className="section-title">Decode</h2>
            </div>

            {/* Signal Inventory */}
            <div className="be-card be-card-accent mb-8">
              <div className="flex items-center gap-2 mb-4">
                <Search className="h-5 w-5 text-gold" />
                <h3 className="font-heading font-bold text-navy">Signal Inventory</h3>
              </div>
              <p className="body-text mb-6">
                The Emotional System communicates through 26 signals across 8 categories:
              </p>

              <div className="grid gap-4 md:grid-cols-2">
                <div>
                  <h4 className="font-heading text-sm font-bold text-navy mb-2">Emotional Range Signals (3)</h4>
                  <ul className="body-text space-y-1">
                    <li>Emotional Numbness / Can&apos;t Feel Emotions</li>
                    <li>Emotional Overwhelm / Too Much Feeling</li>
                    <li>Restricted Emotional Range</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-heading text-sm font-bold text-navy mb-2">Emotional Processing Signals (3)</h4>
                  <ul className="body-text space-y-1">
                    <li>Emotions Get Stuck / Can&apos;t Process Feelings</li>
                    <li>Delayed Emotional Response</li>
                    <li>Disproportionate Emotional Reactions</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-heading text-sm font-bold text-navy mb-2">Specific Emotion Signals (8)</h4>
                  <ul className="body-text space-y-1">
                    <li>Persistent Sadness</li>
                    <li>Persistent Anxiety (Emotional Component)</li>
                    <li>Persistent Anger / Irritability</li>
                    <li>Persistent Shame or Guilt</li>
                    <li>Inability to Feel Joy / Anhedonia</li>
                    <li>Persistent Loneliness</li>
                    <li>Persistent Hopelessness</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-heading text-sm font-bold text-navy mb-2">Emotional Connection Signals (3)</h4>
                  <ul className="body-text space-y-1">
                    <li>Difficulty Connecting Emotionally with Others</li>
                    <li>Difficulty with Emotional Intimacy</li>
                    <li>Difficulty Receiving Care or Love</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-heading text-sm font-bold text-navy mb-2">Emotional Regulation Signals (3)</h4>
                  <ul className="body-text space-y-1">
                    <li>Emotional Volatility / Mood Swings</li>
                    <li>Difficulty Calming Down Once Upset</li>
                    <li>Emotional Outbursts</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-heading text-sm font-bold text-navy mb-2">Emotional Awareness Signals (2)</h4>
                  <ul className="body-text space-y-1">
                    <li>Alexithymia / Can&apos;t Identify Emotions</li>
                    <li>Disconnect Between Thoughts and Feelings</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-heading text-sm font-bold text-navy mb-2">Grief and Loss Signals (2)</h4>
                  <ul className="body-text space-y-1">
                    <li>Unresolved Grief</li>
                    <li>Anticipatory Grief</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-heading text-sm font-bold text-navy mb-2">Emotional Self-Relationship Signals (2)</h4>
                  <ul className="body-text space-y-1">
                    <li>Harsh Inner Critic</li>
                    <li>Difficulty with Self-Compassion</li>
                  </ul>
                </div>
              </div>
            </div>

            {/* TRADE Framework */}
            <div className="be-card mb-8">
              <h3 className="font-heading font-bold text-navy mb-4">The TRADE Framework</h3>
              <p className="body-text mb-6">
                Between your body&apos;s signal and your response, there&apos;s a gap. Most people don&apos;t know it exists.
              </p>

              <div className="space-y-4">
                <div className="flex gap-4">
                  <span className="flex items-center justify-center w-8 h-8 rounded-full bg-gold text-navy font-heading font-bold text-sm flex-shrink-0">T</span>
                  <div>
                    <p className="font-heading font-bold text-navy">Trigger</p>
                    <p className="body-text">You notice heaviness in your chest that&apos;s been there for weeks. Colors seem less vivid. Things that used to bring pleasure feel flat.</p>
                  </div>
                </div>
                <div className="flex gap-4">
                  <span className="flex items-center justify-center w-8 h-8 rounded-full bg-gold text-navy font-heading font-bold text-sm flex-shrink-0">R</span>
                  <div>
                    <p className="font-heading font-bold text-navy">React</p>
                    <p className="body-text">Your body responds. Energy drops. Sleep changes. You withdraw from connections that feel like too much effort.</p>
                  </div>
                </div>
                <div className="flex gap-4">
                  <span className="flex items-center justify-center w-8 h-8 rounded-full bg-gold text-navy font-heading font-bold text-sm flex-shrink-0">A</span>
                  <div>
                    <p className="font-heading font-bold text-navy">Assume</p>
                    <p className="body-text">&quot;I&apos;m broken.&quot; &quot;Something is wrong with me.&quot; &quot;This is just depression.&quot; &quot;I&apos;ve always been this way.&quot; &quot;I&apos;m not an emotional person.&quot; &quot;I should be over this by now.&quot;</p>
                  </div>
                </div>
                <div className="p-4 bg-pink-accent/10 rounded-lg">
                  <p className="body-text italic">
                    Most people live in a loop of T, R, and A. Trigger, react, assume. Trigger, react, assume. The assumption becomes reality, and you end up in a <strong>TRAP</strong>, paralyzed.
                  </p>
                </div>
                <div className="flex gap-4">
                  <span className="flex items-center justify-center w-8 h-8 rounded-full bg-electric-blue text-white font-heading font-bold text-sm flex-shrink-0">D</span>
                  <div>
                    <p className="font-heading font-bold text-navy">Decode</p>
                    <p className="body-text">What if the signal has information? Is there a loss underneath this that hasn&apos;t been fully grieved? When did this start, and what was happening then? Can I feel negative emotions but not positive ones, or is all feeling muted? Is this how I&apos;ve always been, or did something shift?</p>
                  </div>
                </div>
                <div className="flex gap-4">
                  <span className="flex items-center justify-center w-8 h-8 rounded-full bg-electric-blue text-white font-heading font-bold text-sm flex-shrink-0">E</span>
                  <div>
                    <p className="font-heading font-bold text-navy">Encode</p>
                    <p className="body-text">Not &quot;I have depression&quot; but &quot;my emotional system is signaling that something needs attention.&quot; Not &quot;I&apos;m too sensitive&quot; but &quot;my emotional processing capacity may be overwhelmed.&quot; Not &quot;I&apos;m just not an emotional person&quot; but &quot;my system may have learned to protect itself by limiting access to feeling.&quot;</p>
                  </div>
                </div>
              </div>
              <p className="body-text mt-6 text-electric-blue font-medium">
                Investigating takes courage. When you question a story that feels true, you gain more agency over your entire life. This doesn&apos;t stop with your health. This can apply to your career, your family, your friends, anything.
              </p>
            </div>

            {/* Common Mislabels */}
            <div className="be-card">
              <h3 className="font-heading font-bold text-navy mb-4">Common Mislabels</h3>
              <p className="body-text mb-4">
                Emotional signals are frequently attributed to other causes. The following patterns may be worth exploring:
              </p>
              <div className="overflow-x-auto">
                <table className="w-full body-text">
                  <thead>
                    <tr className="border-b border-border">
                      <th className="text-left py-3 pr-4 font-heading text-navy">What It Gets Called</th>
                      <th className="text-left py-3 font-heading text-navy">What It Might Be Worth Exploring</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-b border-border/50">
                      <td className="py-3 pr-4">&quot;Depression&quot;</td>
                      <td className="py-3">Unresolved grief, emotional numbness as protection, anhedonia</td>
                    </tr>
                    <tr className="border-b border-border/50">
                      <td className="py-3 pr-4">&quot;Anxiety disorder&quot;</td>
                      <td className="py-3">Emotional component of worry/dread, unprocessed emotional material</td>
                    </tr>
                    <tr className="border-b border-border/50">
                      <td className="py-3 pr-4">&quot;Being strong&quot;</td>
                      <td className="py-3">Emotional numbness that developed as protection</td>
                    </tr>
                    <tr className="border-b border-border/50">
                      <td className="py-3 pr-4">&quot;Too sensitive&quot;</td>
                      <td className="py-3">Emotional overwhelm, system that processes deeply</td>
                    </tr>
                    <tr className="border-b border-border/50">
                      <td className="py-3 pr-4">&quot;Not an emotional person&quot;</td>
                      <td className="py-3">Restricted emotional range, alexithymia, learned suppression</td>
                    </tr>
                    <tr className="border-b border-border/50">
                      <td className="py-3 pr-4">&quot;Borderline personality&quot;</td>
                      <td className="py-3">Emotional dysregulation, attachment patterns, triggered old wounds</td>
                    </tr>
                    <tr className="border-b border-border/50">
                      <td className="py-3 pr-4">&quot;Anger issues&quot;</td>
                      <td className="py-3">Persistent anger masking sadness or fear, boundary violations</td>
                    </tr>
                    <tr className="border-b border-border/50">
                      <td className="py-3 pr-4">&quot;Being dramatic&quot;</td>
                      <td className="py-3">Emotional overwhelm, disproportionate reactions from triggered material</td>
                    </tr>
                    <tr className="border-b border-border/50">
                      <td className="py-3 pr-4">&quot;High standards&quot;</td>
                      <td className="py-3">Harsh inner critic, difficulty with self-compassion</td>
                    </tr>
                    <tr className="border-b border-border/50">
                      <td className="py-3 pr-4">&quot;Introversion&quot;</td>
                      <td className="py-3">Difficulty connecting emotionally, loneliness, attachment patterns</td>
                    </tr>
                    <tr className="border-b border-border/50">
                      <td className="py-3 pr-4">&quot;Just hormones&quot;</td>
                      <td className="py-3">Emotional volatility originating in emotional processing</td>
                    </tr>
                    <tr className="border-b border-border/50">
                      <td className="py-3 pr-4">&quot;Trust issues&quot;</td>
                      <td className="py-3">Difficulty with emotional intimacy, fear of vulnerability</td>
                    </tr>
                    <tr className="border-b border-border/50">
                      <td className="py-3 pr-4">&quot;Being independent&quot;</td>
                      <td className="py-3">Difficulty receiving care or love, discomfort with vulnerability</td>
                    </tr>
                    <tr>
                      <td className="py-3 pr-4">&quot;Burnout&quot;</td>
                      <td className="py-3">Emotional exhaustion, anhedonia, multiple systems involved</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </section>

          {/* Section 4: Gain */}
          <section>
            <div className="flex items-center gap-3 mb-6">
              <span className="flex items-center justify-center w-10 h-10 rounded-full bg-navy text-white font-heading font-bold">4</span>
              <h2 className="section-title">Gain</h2>
            </div>
            <p className="body-text mb-6">
              These are options to explore. Not prescriptions. Not instructions. Simply possibilities that some have found useful for working with the emotional system.
            </p>

            <div className="grid gap-6 md:grid-cols-2">
              {/* Awareness Tools */}
              <div className="be-card">
                <div className="flex items-center gap-2 mb-4">
                  <Search className="h-5 w-5 text-gold" />
                  <h3 className="font-heading font-bold text-navy">Awareness Tools</h3>
                </div>
                <ul className="space-y-3 body-text">
                  <li>Notice where emotions live in your body (sadness in chest, anger as heat)</li>
                  <li>Track emotional patterns—when do certain feelings arise?</li>
                  <li>Practice naming feelings with specificity (&quot;upset&quot; → disappointment, hurt, fear)</li>
                  <li>Notice what precedes and follows emotional states</li>
                  <li>Build awareness of body&apos;s emotional signals</li>
                </ul>
              </div>

              {/* Exploratory Practices */}
              <div className="be-card">
                <div className="flex items-center gap-2 mb-4">
                  <Sparkles className="h-5 w-5 text-gold" />
                  <h3 className="font-heading font-bold text-navy">Exploratory Practices</h3>
                </div>
                <ul className="space-y-3 body-text">
                  <li>Make space for feelings rather than trying to fix them</li>
                  <li>Somatic practices tracking body sensations with emotional states</li>
                  <li>Creative expression (writing, art, music, movement)</li>
                  <li>Create time without task, input, or distraction for processing</li>
                  <li>Allow emotions to complete without resistance</li>
                </ul>
              </div>

              {/* Environmental Adjustments */}
              <div className="be-card">
                <div className="flex items-center gap-2 mb-4">
                  <Smile className="h-5 w-5 text-gold" />
                  <h3 className="font-heading font-bold text-navy">Environmental Adjustments</h3>
                </div>
                <ul className="space-y-3 body-text">
                  <li>Reduce sensory overwhelm in living spaces</li>
                  <li>Create spaces that feel safe and calming</li>
                  <li>Spend time in nature to down-regulate nervous system</li>
                  <li>Consider the emotional tone of your environments</li>
                </ul>
              </div>

              {/* Professional Resources */}
              <div className="be-card">
                <div className="flex items-center gap-2 mb-4">
                  <LinkIcon className="h-5 w-5 text-gold" />
                  <h3 className="font-heading font-bold text-navy">Professional Resources</h3>
                </div>
                <ul className="space-y-3 body-text">
                  <li>Psychotherapists trained in emotion-focused approaches</li>
                  <li>Somatic therapists</li>
                  <li>Grief counselors</li>
                  <li>Attachment-informed therapists</li>
                  <li>EMDR practitioners for trauma-related patterns</li>
                  <li>Peer support and group therapy for relational healing</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Section 5: Execute */}
          <section>
            <div className="flex items-center gap-3 mb-6">
              <span className="flex items-center justify-center w-10 h-10 rounded-full bg-navy text-white font-heading font-bold">5</span>
              <h2 className="section-title">Execute</h2>
            </div>

            {/* Foundation Practices */}
            <div className="be-card be-card-accent mb-6">
              <div className="flex items-center gap-2 mb-4">
                <Play className="h-5 w-5 text-gold" />
                <h3 className="font-heading font-bold text-navy">Foundation Practices</h3>
              </div>
              <ol className="space-y-4 body-text">
                <li className="flex gap-3">
                  <span className="flex items-center justify-center w-6 h-6 rounded-full bg-navy text-white font-heading font-bold text-xs flex-shrink-0">1</span>
                  <div><strong className="text-navy">Create a daily pause.</strong> Even five minutes without input, where you check in with what you&apos;re feeling, may support emotional awareness and processing.</div>
                </li>
                <li className="flex gap-3">
                  <span className="flex items-center justify-center w-6 h-6 rounded-full bg-navy text-white font-heading font-bold text-xs flex-shrink-0">2</span>
                  <div><strong className="text-navy">Notice where emotions live.</strong> When an emotion arises, notice where it lives in your body before doing anything else. This builds connection between felt experience and awareness.</div>
                </li>
                <li className="flex gap-3">
                  <span className="flex items-center justify-center w-6 h-6 rounded-full bg-navy text-white font-heading font-bold text-xs flex-shrink-0">3</span>
                  <div><strong className="text-navy">End-of-day acknowledgment.</strong> End each day by naming what you felt. Not analyzing, not judging. Just naming: &quot;Today I felt frustrated, tired, and a moment of unexpected joy.&quot;</div>
                </li>
              </ol>
            </div>

            {/* Tracking What You Notice */}
            <div className="be-card mb-6">
              <h3 className="font-heading font-bold text-navy mb-4">Tracking What You Notice</h3>
              <p className="body-text mb-4">Observe rather than optimize. The goal isn&apos;t to fix your emotional life but to understand what it&apos;s communicating:</p>
              <ul className="space-y-3 body-text">
                <li>Notice timing patterns—worse in the morning? At night? After certain interactions?</li>
                <li>Pay attention to what helps and what doesn&apos;t</li>
                <li>Track the duration of emotional states</li>
                <li>How long does it take to return to baseline after upset?</li>
                <li>Has this changed over time?</li>
              </ul>
            </div>

            {/* The Patience Principle */}
            <div className="be-card bg-off-white">
              <h3 className="font-heading font-bold text-navy mb-4">The Patience Principle</h3>
              <p className="body-text mb-4">
                The emotional system operates on its own timeline. Feelings cannot be rushed through or willed away.
              </p>
              <p className="body-text mb-4">
                Emotional patterns, especially those rooted in early experience, may have developed over years or decades. They deserve patient attention, not demands for immediate change. Grief, in particular, takes as long as it takes. There is no standard timeline for processing loss.
              </p>
              <p className="text-electric-blue font-medium">
                Building emotional regulation capacity is like building physical capacity. It happens gradually, with consistent practice, not through force or intensity.
              </p>
            </div>
          </section>

          {/* Section 6: Questions for Clarity */}
          <section>
            <div className="flex items-center gap-3 mb-6">
              <span className="flex items-center justify-center w-10 h-10 rounded-full bg-navy text-white font-heading font-bold">6</span>
              <h2 className="section-title">Questions for Clarity</h2>
            </div>
            <p className="body-text mb-6">
              These questions may help explore whether a signal originates in the Emotional System:
            </p>

            <div className="grid gap-6 md:grid-cols-2">
              <div className="be-card">
                <div className="flex items-center gap-2 mb-4">
                  <HelpCircle className="h-5 w-5 text-gold" />
                  <h3 className="font-heading font-bold text-navy">Core Inquiry</h3>
                </div>
                <ol className="space-y-3 body-text list-decimal list-inside">
                  <li>Is this about a felt emotional experience, or something else?</li>
                  <li>Are specific emotions involved, or is all experience affected?</li>
                  <li>Does this involve your relationship with feelings themselves?</li>
                  <li>Is there a felt quality (heaviness, heat, ache)?</li>
                  <li>Does eating, sleeping, or resting change this signal?</li>
                </ol>
              </div>

              <div className="be-card">
                <div className="flex items-center gap-2 mb-4">
                  <HelpCircle className="h-5 w-5 text-gold" />
                  <h3 className="font-heading font-bold text-navy">Deeper Investigation</h3>
                </div>
                <ol className="space-y-3 body-text list-decimal list-inside">
                  <li>Can you feel negative emotions but not positive ones?</li>
                  <li>Is there unprocessed emotional material (grief, old wounds)?</li>
                  <li>Does emotional support help, or feel threatening?</li>
                  <li>If feelings are accessible but body won&apos;t calm → Stress System</li>
                  <li>If all experience is flat → consider Consciousness System</li>
                </ol>
              </div>
            </div>

            <div className="be-card mt-6">
              <h3 className="font-heading font-bold text-navy mb-4">Distinguishing Overlaps</h3>
              <ul className="space-y-3 body-text">
                <li><strong className="text-navy">Calm body with anxious feelings</strong> → more Emotional involvement</li>
                <li><strong className="text-navy">Anxious body with calm mind</strong> → more Stress System involvement</li>
                <li><strong className="text-navy">All experience thin or gray</strong> → may be Consciousness (quality of awareness)</li>
                <li><strong className="text-navy">Can&apos;t feel emotions while experience remains vivid</strong> → Emotional System</li>
                <li><strong className="text-navy">&quot;Burned out&quot; or &quot;depleted of caring&quot;</strong> → Emotional exhaustion</li>
                <li><strong className="text-navy">Improves with rest and food</strong> → Energy System</li>
              </ul>
            </div>
          </section>

          {/* Section 7: Cross-System Connections */}
          <section>
            <div className="flex items-center gap-3 mb-6">
              <span className="flex items-center justify-center w-10 h-10 rounded-full bg-navy text-white font-heading font-bold">7</span>
              <h2 className="section-title">Cross-System Connections</h2>
            </div>
            <p className="body-text mb-6">
              The Emotional System interfaces with multiple other systems through shared chemical messengers and feedback loops:
            </p>

            <div className="grid gap-4">
              <div className="be-card flex gap-4">
                <div className="w-2 bg-gold rounded-full flex-shrink-0"></div>
                <div>
                  <h4 className="font-heading font-bold text-navy">Stress System</h4>
                  <p className="body-text">Anxiety almost always involves both systems. The Emotional System provides the felt quality of worry or dread. The Stress System provides the physiological activation—racing heart, tight muscles, shallow breath. A calm body with anxious feelings suggests more Emotional involvement.</p>
                </div>
              </div>
              <div className="be-card flex gap-4">
                <div className="w-2 bg-electric-blue rounded-full flex-shrink-0"></div>
                <div>
                  <h4 className="font-heading font-bold text-navy">Consciousness System</h4>
                  <p className="body-text">Feeling flat could be either system. If all experience feels thin or gray, this may be Consciousness (quality of awareness reduced). If specifically unable to feel emotions while other experience remains vivid, this points to Emotional.</p>
                </div>
              </div>
              <div className="be-card flex gap-4">
                <div className="w-2 bg-pink-accent rounded-full flex-shrink-0"></div>
                <div>
                  <h4 className="font-heading font-bold text-navy">Energy Production System</h4>
                  <p className="body-text">Fatigue has different qualities. Emotional exhaustion has a &quot;burned out&quot; or &quot;depleted of caring&quot; quality. Physical exhaustion from the Energy System improves with rest and food. Irritability may involve both systems.</p>
                </div>
              </div>
              <div className="be-card flex gap-4">
                <div className="w-2 bg-deep-blue rounded-full flex-shrink-0"></div>
                <div>
                  <h4 className="font-heading font-bold text-navy">Hormonal System</h4>
                  <p className="body-text">Mood changes may correlate with hormonal cycles (menstrual, diurnal cortisol, thyroid). If emotional signals follow predictable patterns tied to time of day or cycle, the Hormonal System may be involved.</p>
                </div>
              </div>
              <div className="be-card flex gap-4">
                <div className="w-2 bg-gold rounded-full flex-shrink-0"></div>
                <div>
                  <h4 className="font-heading font-bold text-navy">Defense System</h4>
                  <p className="body-text">Inflammation affects mood. Cytokines produced during immune activation can create depression-like states. If emotional flatness accompanies other inflammatory signals, the Defense System may be contributing. Inflammation-driven mood changes often have a flat quality.</p>
                </div>
              </div>
              <div className="be-card flex gap-4">
                <div className="w-2 bg-electric-blue rounded-full flex-shrink-0"></div>
                <div>
                  <h4 className="font-heading font-bold text-navy">Regeneration System</h4>
                  <p className="body-text">Sleep deprivation reliably affects emotional regulation. When the Regeneration System is compromised, emotional volatility, irritability, and overwhelm often increase. Improving sleep sometimes resolves what appeared to be primary emotional difficulties.</p>
                </div>
              </div>
            </div>
          </section>

          {/* Closing */}
          <section className="be-card be-card-accent text-center">
            <p className="body-text text-navy mb-4">
              Your body already knows how to feel. You were born with this capacity intact. Before you had words, you had feelings. Before you could name what was happening, you could sense its meaning.
            </p>
            <p className="body-text italic">
              The question is whether you&apos;re creating the conditions for your emotional system to do what it already knows how to do.
            </p>
          </section>

          {/* Navigation */}
          <div className="flex justify-between items-center pt-8 border-t border-border">
            <Link
              href="/systems/digestive"
              className="inline-flex items-center gap-2 text-sm text-text-light hover:text-gold transition-colors"
            >
              <ArrowLeft className="h-4 w-4" />
              Previous: Digestive
            </Link>
            <Link
              href="/systems/energy-production"
              className="inline-flex items-center gap-2 text-sm text-gold hover:text-pink-accent transition-colors font-medium"
            >
              Next: Energy Production
              <ArrowLeft className="h-4 w-4 rotate-180" />
            </Link>
          </div>
        </div>
      </div>
    </>
  )
}

export const metadata = {
  title: "Emotional System | bioEDGE Decoder",
  description: "Your Body's Meaning Maker. The Emotional System governs the felt experience of being alive—taking raw experience and transforming it into meaning you can feel.",
}
