import { ArrowLeft } from "lucide-react"
import Link from "next/link"
import { Suspense } from "react"
import { SystemDirectory } from "@/components/directory/system-solutions"

/**
 * Emotional System Page
 *
 * Your Body's Meaning Maker - mental wellbeing, mood regulation, psychological health
 * Part of the bioEDGE Decoder 15 Systems Framework.
 */
export default function EmotionalSystemPage() {
  return (
    <>
      {/* Hero */}
      <div className="be-event-hero">
        <div className="be-container py-16 relative z-10">
          <Link
            href="/systems"
            className="inline-flex items-center gap-2 text-sm text-white/70 hover:text-gold transition-colors mb-6"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to All Systems
          </Link>
          <h1 className="font-heading text-4xl md:text-5xl font-bold tracking-tight text-white mb-4">
            Emotional System
          </h1>
          <p className="text-xl text-white/80 max-w-2xl">
            Your Body&apos;s Meaning Maker
          </p>
          <p className="text-sm text-gold mt-4 font-heading uppercase tracking-wider">
            bioEDGE Decoder
          </p>
        </div>
      </div>

      {/* Section Nav */}
      <nav className="border-b border-border bg-white/80 backdrop-blur-sm sticky top-0 z-20">
        <div className="be-container">
          <div className="max-w-3xl mx-auto flex flex-wrap gap-x-6 gap-y-2 py-3 text-sm">
            <a href="#natural-intelligence" className="text-text-light hover:text-navy transition-colors">Natural Intelligence</a>
            <a href="#eliminate" className="text-text-light hover:text-navy transition-colors">Eliminate</a>
            <a href="#decode" className="text-text-light hover:text-navy transition-colors">Decode</a>
            <a href="#gain" className="text-text-light hover:text-navy transition-colors">Gain</a>
            <a href="#execute" className="text-text-light hover:text-navy transition-colors">Execute</a>
            <a href="#questions" className="text-text-light hover:text-navy transition-colors">Questions</a>
            <a href="#connections" className="text-text-light hover:text-navy transition-colors">Connections</a>
            <a href="#directory" className="text-text-light hover:text-navy transition-colors">Directory</a>
          </div>
        </div>
      </nav>

      {/* Content */}
      <div className="be-container py-12">
        <div className="max-w-3xl mx-auto">
          <article className="space-y-8 body-text">

            {/* Natural Intelligence */}

            <div id="natural-intelligence" className="border-l-4 pl-6 py-2 scroll-mt-16" style={{ borderColor: "#0d2840" }}>
              <h2 className="font-heading font-bold text-2xl text-navy">
                Natural Intelligence
              </h2>
            </div>

            <p>
              The Emotional System governs the felt experience of being alive. It takes raw experience and transforms it into meaning you can feel.
            </p>

            <p>
              This system processes. Not just information, but sensation. Not just events, but their significance to you. When something happens, this system tells you what it means before your thinking mind has a chance to analyze it.
            </p>

            <p>
              <strong className="text-navy">What makes this system unique among the fourteen: it is where experience becomes personal.</strong> The Stress System might tell your body there&apos;s danger. The Consciousness System might observe what&apos;s happening. But the Emotional System is where you feel that danger as fear, where you experience that observation as wonder or dread or curiosity. It&apos;s the difference between knowing something and feeling it.
            </p>

            <p>
              Emotions are not character flaws. They are not chemical imbalances to be corrected. They are embodied states with clear biological signatures, generated by brain structures including the amygdala, hippocampus, and insula. Antonio Damasio demonstrated in the 1990s that emotions are essential to rational decision-making, not obstacles to it. People with damage to emotion-processing brain regions don&apos;t become more logical. They become less able to make decisions at all.
            </p>

            <p>
              Here is your psychophysiological supersystem at work: the same chemical messengers that signal your immune system to respond to threat also shift your emotional state. The hormones that regulate your metabolism also color your mood. The nervous system that governs your stress response also determines whether you can access feelings of safety and connection. These systems don&apos;t hold committee meetings. They communicate constantly through shared messengers and feedback loops so integrated that affecting one inevitably affects the others.
            </p>

            <p>
              Your body already knows how to feel. You were born with this capacity intact. Before you had words, you had feelings. Before you could name what was happening, you could sense its meaning. This wisdom is encoded in your biology, not in concepts, but in what your nervous system knows how to do.
            </p>

            <p>
              The question isn&apos;t whether your emotional system is working. It&apos;s whether you&apos;re able to hear what it&apos;s telling you.
            </p>

            {/* Eliminate */}

            <div id="eliminate" className="border-l-4 pl-6 py-2 scroll-mt-16" style={{ borderColor: "#0d2840" }}>
              <h2 className="font-heading font-bold text-2xl text-navy">
                Eliminate
              </h2>
              <p className="text-sm font-heading mt-1" style={{ color: "#0d598a" }}>Identify and remove interference</p>
            </div>

            <p>
              These are factors worth examining. Not causes. Not diagnoses. Simply elements that may be interfering with your emotional system&apos;s natural function.
            </p>

            <h3 className="font-heading font-bold text-navy">Lifestyle Factors</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Sleep deprivation amplifying emotional volatility and overwhelm</li>
              <li>Sedentary patterns associated with stuck emotional states</li>
              <li>Calendar with no margin leaving no space for emotional processing</li>
              <li>Feelings accumulating when there&apos;s no time to feel them</li>
            </ul>

            <h3 className="font-heading font-bold text-navy">Dietary Considerations</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Blood sugar fluctuations influencing emotional regulation</li>
              <li>Alcohol, excessive caffeine affecting mood and processing</li>
              <li>Highly processed foods associated with emotional volatility</li>
              <li>Gut health influencing emotional states through gut-brain axis</li>
            </ul>

            <h3 className="font-heading font-bold text-navy">Environmental Interference</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Chronic noise, clutter, or chaos contributing to overwhelm</li>
              <li>Toxic environments (mold, chemicals) affecting mood through inflammation</li>
              <li>Limited natural light affecting emotional experience</li>
            </ul>

            <h3 className="font-heading font-bold text-navy">Relationship &amp; Emotional Patterns</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Relationships where emotional expression is unwelcome</li>
              <li>Unresolved relational wounds keeping system in protective patterns</li>
              <li>Chronic loneliness affecting emotional health</li>
              <li>Past betrayals or invalidations shaping current accessibility</li>
            </ul>

            <h3 className="font-heading font-bold text-navy">Habitual Patterns</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Chronic suppression leading to numbness or explosive outbursts</li>
              <li>Emotional avoidance through busyness, substances, or distraction</li>
              <li>Habitual emotional roles (&quot;strong one,&quot; &quot;caretaker&quot;) suppressing needs</li>
            </ul>

            <h3 className="font-heading font-bold text-navy">Digital Interference</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Screen time interfering with quieter emotional processing</li>
              <li>Social media comparison contributing to shame or inadequacy</li>
              <li>Notification patterns fragmenting attention needed for processing</li>
            </ul>

            {/* Decode */}

            <div id="decode" className="border-l-4 pl-6 py-2 scroll-mt-16" style={{ borderColor: "#0d2840" }}>
              <h2 className="font-heading font-bold text-2xl text-navy">
                Decode
              </h2>
              <p className="text-sm font-heading mt-1" style={{ color: "#0d598a" }}>Understand what your body is communicating</p>
            </div>

            <h3 className="font-heading font-bold text-navy">Signal Inventory</h3>

            <p>
              The Emotional System communicates through 26 signals across 8 categories:
            </p>

            <h4 className="font-heading text-sm font-bold text-navy">Emotional Range Signals (3)</h4>
            <ul className="list-disc pl-6 space-y-1">
              <li>Emotional Numbness / Can&apos;t Feel Emotions</li>
              <li>Emotional Overwhelm / Too Much Feeling</li>
              <li>Restricted Emotional Range</li>
            </ul>

            <h4 className="font-heading text-sm font-bold text-navy">Emotional Processing Signals (3)</h4>
            <ul className="list-disc pl-6 space-y-1">
              <li>Emotions Get Stuck / Can&apos;t Process Feelings</li>
              <li>Delayed Emotional Response</li>
              <li>Disproportionate Emotional Reactions</li>
            </ul>

            <h4 className="font-heading text-sm font-bold text-navy">Specific Emotion Signals (8)</h4>
            <ul className="list-disc pl-6 space-y-1">
              <li>Persistent Sadness</li>
              <li>Persistent Anxiety (Emotional Component)</li>
              <li>Persistent Anger / Irritability</li>
              <li>Persistent Shame or Guilt</li>
              <li>Inability to Feel Joy / Anhedonia</li>
              <li>Persistent Loneliness</li>
              <li>Persistent Hopelessness</li>
            </ul>

            <h4 className="font-heading text-sm font-bold text-navy">Emotional Connection Signals (3)</h4>
            <ul className="list-disc pl-6 space-y-1">
              <li>Difficulty Connecting Emotionally with Others</li>
              <li>Difficulty with Emotional Intimacy</li>
              <li>Difficulty Receiving Care or Love</li>
            </ul>

            <h4 className="font-heading text-sm font-bold text-navy">Emotional Regulation Signals (3)</h4>
            <ul className="list-disc pl-6 space-y-1">
              <li>Emotional Volatility / Mood Swings</li>
              <li>Difficulty Calming Down Once Upset</li>
              <li>Emotional Outbursts</li>
            </ul>

            <h4 className="font-heading text-sm font-bold text-navy">Emotional Awareness Signals (2)</h4>
            <ul className="list-disc pl-6 space-y-1">
              <li>Alexithymia / Can&apos;t Identify Emotions</li>
              <li>Disconnect Between Thoughts and Feelings</li>
            </ul>

            <h4 className="font-heading text-sm font-bold text-navy">Grief and Loss Signals (2)</h4>
            <ul className="list-disc pl-6 space-y-1">
              <li>Unresolved Grief</li>
              <li>Anticipatory Grief</li>
            </ul>

            <h4 className="font-heading text-sm font-bold text-navy">Emotional Self-Relationship Signals (2)</h4>
            <ul className="list-disc pl-6 space-y-1">
              <li>Harsh Inner Critic</li>
              <li>Difficulty with Self-Compassion</li>
            </ul>

            <h3 className="font-heading font-bold text-navy">The TRADE Framework</h3>

            <p>
              Between your body&apos;s signal and your response, there&apos;s a gap. Most people don&apos;t know it exists.
            </p>

            <p>
              <strong className="text-navy">T — Trigger:</strong> You notice heaviness in your chest that&apos;s been there for weeks. Colors seem less vivid. Things that used to bring pleasure feel flat.
            </p>

            <p>
              <strong className="text-navy">R — React:</strong> Your body responds. Energy drops. Sleep changes. You withdraw from connections that feel like too much effort.
            </p>

            <p>
              <strong className="text-navy">A — Assume:</strong> &quot;I&apos;m broken.&quot; &quot;Something is wrong with me.&quot; &quot;This is just depression.&quot; &quot;I&apos;ve always been this way.&quot; &quot;I&apos;m not an emotional person.&quot; &quot;I should be over this by now.&quot;
            </p>

            <p>
              <em>Most people live in a loop of T, R, and A. Trigger, react, assume. Trigger, react, assume. The assumption becomes reality, and you end up in a <strong>TRAP</strong>, paralyzed.</em>
            </p>

            <p>
              <strong className="text-navy">D — Decode:</strong> What if the signal has information? Is there a loss underneath this that hasn&apos;t been fully grieved? When did this start, and what was happening then? Can I feel negative emotions but not positive ones, or is all feeling muted? Is this how I&apos;ve always been, or did something shift?
            </p>

            <p>
              <strong className="text-navy">E — Encode:</strong> Not &quot;I have depression&quot; but &quot;my emotional system is signaling that something needs attention.&quot; Not &quot;I&apos;m too sensitive&quot; but &quot;my emotional processing capacity may be overwhelmed.&quot; Not &quot;I&apos;m just not an emotional person&quot; but &quot;my system may have learned to protect itself by limiting access to feeling.&quot;
            </p>

            <p>
              Investigating takes courage. When you question a story that feels true, you gain more agency over your entire life. This doesn&apos;t stop with your health. This can apply to your career, your family, your friends, anything.
            </p>

            <h3 className="font-heading font-bold text-navy">Common Mislabels</h3>

            <p>
              Emotional signals are frequently attributed to other causes. The following patterns may be worth exploring:
            </p>

            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-border">
                    <th className="text-left py-3 pr-4 font-heading text-navy">What It Gets Called</th>
                    <th className="text-left py-3 font-heading text-navy">What It Might Be Worth Exploring</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-border/50">
                    <td className="py-3 pr-4">&quot;Depression&quot;</td>
                    <td className="py-3">Unresolved grief, emotional numbness as protection, anhedonia</td>
                  </tr>
                  <tr className="border-b border-border/50">
                    <td className="py-3 pr-4">&quot;Anxiety disorder&quot;</td>
                    <td className="py-3">Emotional component of worry/dread, unprocessed emotional material</td>
                  </tr>
                  <tr className="border-b border-border/50">
                    <td className="py-3 pr-4">&quot;Being strong&quot;</td>
                    <td className="py-3">Emotional numbness that developed as protection</td>
                  </tr>
                  <tr className="border-b border-border/50">
                    <td className="py-3 pr-4">&quot;Too sensitive&quot;</td>
                    <td className="py-3">Emotional overwhelm, system that processes deeply</td>
                  </tr>
                  <tr className="border-b border-border/50">
                    <td className="py-3 pr-4">&quot;Not an emotional person&quot;</td>
                    <td className="py-3">Restricted emotional range, alexithymia, learned suppression</td>
                  </tr>
                  <tr className="border-b border-border/50">
                    <td className="py-3 pr-4">&quot;Borderline personality&quot;</td>
                    <td className="py-3">Emotional dysregulation, attachment patterns, triggered old wounds</td>
                  </tr>
                  <tr className="border-b border-border/50">
                    <td className="py-3 pr-4">&quot;Anger issues&quot;</td>
                    <td className="py-3">Persistent anger masking sadness or fear, boundary violations</td>
                  </tr>
                  <tr className="border-b border-border/50">
                    <td className="py-3 pr-4">&quot;Being dramatic&quot;</td>
                    <td className="py-3">Emotional overwhelm, disproportionate reactions from triggered material</td>
                  </tr>
                  <tr className="border-b border-border/50">
                    <td className="py-3 pr-4">&quot;High standards&quot;</td>
                    <td className="py-3">Harsh inner critic, difficulty with self-compassion</td>
                  </tr>
                  <tr className="border-b border-border/50">
                    <td className="py-3 pr-4">&quot;Introversion&quot;</td>
                    <td className="py-3">Difficulty connecting emotionally, loneliness, attachment patterns</td>
                  </tr>
                  <tr className="border-b border-border/50">
                    <td className="py-3 pr-4">&quot;Just hormones&quot;</td>
                    <td className="py-3">Emotional volatility originating in emotional processing</td>
                  </tr>
                  <tr className="border-b border-border/50">
                    <td className="py-3 pr-4">&quot;Trust issues&quot;</td>
                    <td className="py-3">Difficulty with emotional intimacy, fear of vulnerability</td>
                  </tr>
                  <tr className="border-b border-border/50">
                    <td className="py-3 pr-4">&quot;Being independent&quot;</td>
                    <td className="py-3">Difficulty receiving care or love, discomfort with vulnerability</td>
                  </tr>
                  <tr>
                    <td className="py-3 pr-4">&quot;Burnout&quot;</td>
                    <td className="py-3">Emotional exhaustion, anhedonia, multiple systems involved</td>
                  </tr>
                </tbody>
              </table>
            </div>

            {/* Gain */}

            <div id="gain" className="border-l-4 pl-6 py-2 scroll-mt-16" style={{ borderColor: "#0d2840" }}>
              <h2 className="font-heading font-bold text-2xl text-navy">
                Gain
              </h2>
              <p className="text-sm font-heading mt-1" style={{ color: "#0d598a" }}>Explore supportive practices and resources</p>
            </div>

            <p>
              These are options to explore. Not prescriptions. Not instructions. Simply possibilities that some have found useful for working with the emotional system.
            </p>

            <h3 className="font-heading font-bold text-navy">Awareness Tools</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Notice where emotions live in your body (sadness in chest, anger as heat)</li>
              <li>Track emotional patterns—when do certain feelings arise?</li>
              <li>Practice naming feelings with specificity (&quot;upset&quot; → disappointment, hurt, fear)</li>
              <li>Notice what precedes and follows emotional states</li>
              <li>Build awareness of body&apos;s emotional signals</li>
            </ul>

            <h3 className="font-heading font-bold text-navy">Exploratory Practices</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Make space for feelings rather than trying to fix them</li>
              <li>Somatic practices tracking body sensations with emotional states</li>
              <li>Creative expression (writing, art, music, movement)</li>
              <li>Create time without task, input, or distraction for processing</li>
              <li>Allow emotions to complete without resistance</li>
            </ul>

            <h3 className="font-heading font-bold text-navy">Environmental Adjustments</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Reduce sensory overwhelm in living spaces</li>
              <li>Create spaces that feel safe and calming</li>
              <li>Spend time in nature to down-regulate nervous system</li>
              <li>Consider the emotional tone of your environments</li>
            </ul>

            <h3 className="font-heading font-bold text-navy">Professional Resources</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Psychotherapists trained in emotion-focused approaches</li>
              <li>Somatic therapists</li>
              <li>Grief counselors</li>
              <li>Attachment-informed therapists</li>
              <li>EMDR practitioners for trauma-related patterns</li>
              <li>Peer support and group therapy for relational healing</li>
            </ul>

            {/* Execute */}

            <div id="execute" className="border-l-4 pl-6 py-2 scroll-mt-16" style={{ borderColor: "#0d2840" }}>
              <h2 className="font-heading font-bold text-2xl text-navy">
                Execute
              </h2>
              <p className="text-sm font-heading mt-1" style={{ color: "#0d598a" }}>Take action with patience and consistency</p>
            </div>

            <h3 className="font-heading font-bold text-navy">Foundation Practices</h3>

            <p>Simple anchors that may support emotional awareness:</p>

            <ol className="list-decimal pl-6 space-y-3">
              <li><strong className="text-navy">Create a daily pause.</strong> Even five minutes without input, where you check in with what you&apos;re feeling, may support emotional awareness and processing.</li>
              <li><strong className="text-navy">Notice where emotions live.</strong> When an emotion arises, notice where it lives in your body before doing anything else. This builds connection between felt experience and awareness.</li>
              <li><strong className="text-navy">End-of-day acknowledgment.</strong> End each day by naming what you felt. Not analyzing, not judging. Just naming: &quot;Today I felt frustrated, tired, and a moment of unexpected joy.&quot;</li>
            </ol>

            <h3 className="font-heading font-bold text-navy">Tracking What You Notice</h3>

            <p>Observe rather than optimize. The goal isn&apos;t to fix your emotional life but to understand what it&apos;s communicating:</p>

            <ul className="list-disc pl-6 space-y-2">
              <li>Notice timing patterns—worse in the morning? At night? After certain interactions?</li>
              <li>Pay attention to what helps and what doesn&apos;t</li>
              <li>Track the duration of emotional states</li>
              <li>How long does it take to return to baseline after upset?</li>
              <li>Has this changed over time?</li>
            </ul>

            <h3 className="font-heading font-bold text-navy">The Patience Principle</h3>

            <p>
              The emotional system operates on its own timeline. Feelings cannot be rushed through or willed away.
            </p>

            <p>
              Emotional patterns, especially those rooted in early experience, may have developed over years or decades. They deserve patient attention, not demands for immediate change. Grief, in particular, takes as long as it takes. There is no standard timeline for processing loss.
            </p>

            <p>
              Building emotional regulation capacity is like building physical capacity. It happens gradually, with consistent practice, not through force or intensity.
            </p>

            {/* Questions for Clarity */}

            <div id="questions" className="border-l-4 pl-6 py-2 scroll-mt-16" style={{ borderColor: "#0d2840" }}>
              <h2 className="font-heading font-bold text-2xl text-navy">
                Questions for Clarity
              </h2>
            </div>

            <p>
              These questions may help explore whether a signal originates in the Emotional System:
            </p>

            <h3 className="font-heading font-bold text-navy">Core Inquiry</h3>
            <ol className="list-decimal pl-6 space-y-2">
              <li>Is this about a felt emotional experience, or something else?</li>
              <li>Are specific emotions involved, or is all experience affected?</li>
              <li>Does this involve your relationship with feelings themselves?</li>
              <li>Is there a felt quality (heaviness, heat, ache)?</li>
              <li>Does eating, sleeping, or resting change this signal?</li>
            </ol>

            <h3 className="font-heading font-bold text-navy">Deeper Investigation</h3>
            <ol className="list-decimal pl-6 space-y-2">
              <li>Can you feel negative emotions but not positive ones?</li>
              <li>Is there unprocessed emotional material (grief, old wounds)?</li>
              <li>Does emotional support help, or feel threatening?</li>
              <li>If feelings are accessible but body won&apos;t calm → Stress System</li>
              <li>If all experience is flat → consider Consciousness System</li>
            </ol>

            <h3 className="font-heading font-bold text-navy">Distinguishing Overlaps</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong className="text-navy">Calm body with anxious feelings</strong> → more Emotional involvement</li>
              <li><strong className="text-navy">Anxious body with calm mind</strong> → more Stress System involvement</li>
              <li><strong className="text-navy">All experience thin or gray</strong> → may be Consciousness (quality of awareness)</li>
              <li><strong className="text-navy">Can&apos;t feel emotions while experience remains vivid</strong> → Emotional System</li>
              <li><strong className="text-navy">&quot;Burned out&quot; or &quot;depleted of caring&quot;</strong> → Emotional exhaustion</li>
              <li><strong className="text-navy">Improves with rest and food</strong> → Energy System</li>
            </ul>

            {/* Cross-System Connections */}

            <div id="connections" className="border-l-4 pl-6 py-2 scroll-mt-16" style={{ borderColor: "#0d2840" }}>
              <h2 className="font-heading font-bold text-2xl text-navy">
                Cross-System Connections
              </h2>
            </div>

            <p>
              The Emotional System interfaces with multiple other systems through shared chemical messengers and feedback loops:
            </p>

            <p>
              <strong className="text-navy">Stress System</strong> — Anxiety almost always involves both systems. The Emotional System provides the felt quality of worry or dread. The Stress System provides the physiological activation—racing heart, tight muscles, shallow breath. A calm body with anxious feelings suggests more Emotional involvement.
            </p>

            <p>
              <strong className="text-navy">Consciousness System</strong> — Feeling flat could be either system. If all experience feels thin or gray, this may be Consciousness (quality of awareness reduced). If specifically unable to feel emotions while other experience remains vivid, this points to Emotional.
            </p>

            <p>
              <strong className="text-navy">Energy Production System</strong> — Fatigue has different qualities. Emotional exhaustion has a &quot;burned out&quot; or &quot;depleted of caring&quot; quality. Physical exhaustion from the Energy System improves with rest and food. Irritability may involve both systems.
            </p>

            <p>
              <strong className="text-navy">Hormonal System</strong> — Mood changes may correlate with hormonal cycles (menstrual, diurnal cortisol, thyroid). If emotional signals follow predictable patterns tied to time of day or cycle, the Hormonal System may be involved.
            </p>

            <p>
              <strong className="text-navy">Defense System</strong> — Inflammation affects mood. Cytokines produced during immune activation can create depression-like states. If emotional flatness accompanies other inflammatory signals, the Defense System may be contributing. Inflammation-driven mood changes often have a flat quality.
            </p>

            <p>
              <strong className="text-navy">Regeneration System</strong> — Sleep deprivation reliably affects emotional regulation. When the Regeneration System is compromised, emotional volatility, irritability, and overwhelm often increase. Improving sleep sometimes resolves what appeared to be primary emotional difficulties.
            </p>


            <Suspense fallback={null}>
              <SystemDirectory system="Emotional" label="Emotional" />
            </Suspense>

            {/* Closing */}

            <div className="border-t border-border pt-10 mt-10">
              <p>
                Your body already knows how to feel. You were born with this capacity intact. Before you had words, you had feelings. Before you could name what was happening, you could sense its meaning.
              </p>
              <p className="mt-4 italic">
                The question is whether you&apos;re creating the conditions for your emotional system to do what it already knows how to do.
              </p>
            </div>

          </article>

          {/* Navigation */}
          <div className="flex justify-between items-center pt-8 border-t border-border mt-12">
            <Link
              href="/systems/digestive"
              className="inline-flex items-center gap-2 text-sm text-text-light hover:text-gold transition-colors"
            >
              <ArrowLeft className="h-4 w-4" />
              Previous: Digestive
            </Link>
            <Link
              href="/systems/energy-production"
              className="inline-flex items-center gap-2 text-sm text-[#017ab2] hover:text-navy transition-colors font-medium"
            >
              Next: Energy Production
              <ArrowLeft className="h-4 w-4 rotate-180" />
            </Link>
          </div>
        </div>
      </div>
    </>
  )
}

export const metadata = {
  title: "Emotional System | bioEDGE Decoder",
  description: "Your Body's Meaning Maker. The Emotional System governs the felt experience of being alive—taking raw experience and transforming it into meaning you can feel.",
}
